version: "2"
run:
  modules-download-mode: readonly
  issues-exit-code: 0
output:
  formats:
    text:
      path: stdout
      colors: true
linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - errname
    - goconst
    - gocyclo
    - godot
    - govet
    - ineffassign
    - mnd
    - nestif
    - staticcheck
    - unconvert
  settings:
    tagliatelle:
      case:
        rules:
          envconfig: lower
          json: camel
          yaml: camel
        use-field-name: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: false
severity:
  default: info
formatters:
  enable:
    - gci
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
