package env

const (
	KLIO_LOG_LEVEL                          = "KLIO_LOG_LEVEL"
	KLIO_SKIP_UPDATE_CHECK                  = "KLIO_SKIP_UPDATE_CHECK"
	KLIO_SKIP_PROJECT_COMMAND_AUTO_DOWNLOAD = "KLIO_SKIP_PROJECT_COMMAND_AUTO_DOWNLOAD"
)
