name: Prepare release

on: workflow_dispatch

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Bump version
      uses: qzb/standard-version-action@v1.0.1

    - name: Get version
      id: get-version
      run: |
        echo ::set-output name=version::$(cat VERSION)

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        body: ""
        branch: "release/v${{steps.get-version.outputs.version}}"
        commit-message: "chore(release): ${{steps.get-version.outputs.version}}"
        delete-branch: true
        title: "Release v${{steps.get-version.outputs.version}}"
